apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-nginx-test
  labels:
    app: nginx-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    app: nginx-test
